kafka:
  servers: 'localhost:9092'
  topic: 'mulesoft-kafka-poc'
  groupId: 'grupo-consumidor'
  
schema-registry:
  url: 'http://localhost:8888'
  
postgresql:
  url: 'jdbc:postgresql://localhost:5432/learnMule'
  user: 'postgres'
  password: 'Teste@123'